SELECT SP.SUPPLIER_CODE, 
PR.INTERNAL_CODE, PR.NATIONAL_CODE,PR.DESCRIPTION AS PRODUCT_DESCRIPTION,
PL.WAREHOUSE_CODE 
FROM PRODUCT PR 
JOIN SUPPLIER_PRODUCT SP ON SP.ID_PRODUCT=PR.ID 
JOIN PRODUCT_LOGISTIC PL ON PL.INTERNAL_CODE=PR.INTERNAL_CODE 
JOIN PRODUCT_PACKAGING PP ON PP.ID_PRODUCT_LOGISTIC=PL.ID 
JOIN PRODUCT_PACK_SLOT_ASSIGN PPSA ON PPSA.ID_PRODUCT_PACKAGING=PP.ID 
JOIN SLOT SL ON SL.CODE=PPSA.SLOT_CODE 
JOIN SLOT_RANGE SR ON SR.ID=SL.ID_SLOT_RANGE AND SR.WAREHOUSE_CODE=PL.WAREHOUSE_CODE 
WHERE 1=1 
AND SP.TYPE ='PRIMARY' 
AND SL.TYPE='Pick_Slot' AND PPSA.PREDEFINED=1 
AND PL.WAREHOUSE_CODE=? 