SELECT  DISTINCT S.INTERNAL_CODE,S.WAREHOUSE_CODE, 
P.INTERNAL_CODE,P.NATIONAL_CODE, P.DESCRIPTION 
FROM PRODUCT P 
JOIN STOCK S ON S.INTERNAL_CODE=P.INTERNAL_CODE 
JOIN STOCK_GROUP SG ON S.ID=SG.ID_STOCK 
JOIN STOCK_ITEM SI ON SI.ID_STOCK_GROUP=SG.ID 
JOIN STOCK_GROUP_SLOT_LINK SGSL ON SGSL.ID_STOCK_GROUP=SG.ID 
JOIN SLOT SL ON SL.CODE=SGSL.SLOT_CODE 
JOIN SLOT_RANGE SLR ON SLR.ID=SL.ID_SLOT_RANGE AND SLR.WAREHOUSE_CODE=S.WAREHOUSE_CODE 
WHERE 1=1 
AND S.WAREHOUSE_CODE='610' 
AND SG.STATUS ='Active' 
AND SL.TYPE IN ('Pick_Slot','Reserve_Slot') 
AND SI.TYPE='PBOH - Pick BOH' 
AND SI.QUANTITY>0 